var num = 3;
var num2 = 5;
var result = num + num2;
console.log(result);
var x = 12;
var y = 4;
var z = x - y;
console.log("".concat(z));
var a = 4;
var b = 2;
var c = 4 * b;
console.log(c);
var num3 = 16;
var num4 = 2;
console.log(num3 / num4);
